import re
from src.config import (
    DB1_KEYWORDS,
    DB2_KEYWORDS,
    LLM_KEYWORDS,
    KNOWN_CROPS,
    KNOWN_LOCATIONS,
    SQL_TEMPLATES,
)


class AlgorithmicDecomposer:
    """
    Decomposes a query using keyword matching, entity extraction, and rule-based logic.
    """

    def __init__(self):
        print("Algorithmic Decomposer Initialized.")

    def _extract_entities(self, query):
        """A simple entity extractor based on predefined lists."""
        entities = {"crops": [], "locations": [], "year": None, "soil_type": []}

        # Extract crops
        for crop in KNOWN_CROPS:
            if crop in query:
                entities["crops"].append(crop.capitalize())

        # Extract locations
        for loc in KNOWN_LOCATIONS:
            if loc in query:
                entities["locations"].append(loc.capitalize())

        # Extract year (a simple 4-digit number)
        year_match = re.search(r"\\b(20\\d{2})\\b", query)
        if year_match:
            entities["year"] = int(year_match.group(1))

        # Extract soil type (simple match)
        if "alluvial soil" in query:
            entities["soil_type"].append("Alluvial")
        if "clay soil" in query:
            entities["soil_type"].append("Clay")
        if "sandy loam" in query:
            entities["soil_type"].append("Sandy Loam")
        if "silt soil" in query:
            entities["soil_type"].append("Silt")

        return entities

    def decompose(self, user_query: str):
        """
        Analyzes the query and returns a decomposed plan.
        """
        query_lower = user_query.lower()
        entities = self._extract_entities(query_lower)

        plan = {
            "analysis": "Plan generated by the rule-based algorithmic decomposer.",
            "db1_sql": "N/A",
            "db2_sql": "N/A",
            "llm_prompt": "N/A",
        }

        # Determine intents based on keywords
        use_db1 = any(kw in query_lower for kw in DB1_KEYWORDS)
        use_db2 = any(kw in query_lower for kw in DB2_KEYWORDS)
        use_llm = any(kw in query_lower for kw in LLM_KEYWORDS)

        # --- Rule-Based Logic ---

        # Rule 1: Simple DB2 query for yield
        if (
            use_db2
            and "average yield" in query_lower
            and entities["crops"]
            and entities["locations"]
            and entities["year"]
        ):
            sql = SQL_TEMPLATES["avg_yield_by_crop_location_year"]
            sql = sql.replace("<LOCATION>", entities["locations"][0])
            sql = sql.replace("<CROP>", entities["crops"][0])
            sql = sql.replace("<YEAR>", str(entities["year"]))
            plan["db2_sql"] = sql

        # Rule 2: Simple DB1 query for soil pH
        elif use_db1 and "average soil ph" in query_lower and entities["locations"]:
            sql = SQL_TEMPLATES["avg_ph_by_location"]
            sql = sql.replace("<LOCATION>", entities["locations"][0])
            plan["db1_sql"] = sql

        # Rule 3: Chained query (DB1 -> DB2)
        elif (
            use_db1
            and use_db2
            and entities["locations"]
            and entities["crops"]
            and entities["soil_type"]
        ):
            db1_sql = SQL_TEMPLATES["districts_by_soil_type"]
            db1_sql = db1_sql.replace("<LOCATION>", entities["locations"][0])
            db1_sql = db1_sql.replace("<SOIL_TYPE>", entities["soil_type"][0])
            plan["db1_sql"] = db1_sql

            db2_sql = SQL_TEMPLATES["avg_yield_by_district_list"]
            db2_sql = db2_sql.replace("<CROP>", entities["crops"][0])
            db2_sql = db2_sql.replace(
                "<DISTRICT_IDS>", "<LIST_OF_DISTRICT_IDS_FROM_DB1>"
            )
            plan["db2_sql"] = db2_sql

        if use_llm:
            # Instead of passing the whole query, we try to isolate the "knowledge" part.
            # This is a simple implementation; a real-world version would be more complex.

            # Find the "action phrase" triggered by an LLM keyword.
            # We split the query at the keyword to get the relevant part.
            llm_focus = ""
            for keyword in LLM_KEYWORDS:
                if keyword in query_lower:
                    # Split the string at the keyword and take the part after it.
                    parts = query_lower.split(keyword, 1)
                    if len(parts) > 1:
                        llm_focus = keyword + parts[1]
                        break

            # If we successfully isolated a phrase, we can build a better prompt.
            if llm_focus and entities["crops"] and entities["locations"]:
                plan["llm_prompt"] = (
                    f"Provide information on: '{llm_focus.strip()}' for the crop '{entities['crops'][0]}' in '{entities['locations'][0]}'."
                )
            elif llm_focus:
                plan["llm_prompt"] = f"Provide information on: '{llm_focus.strip()}'."
            else:
                # Fallback to the original query if our simple logic fails
                plan["llm_prompt"] = user_query

        return plan
