# This file stores the keywords and templates for the algorithmic decomposer.

# Keywords to identify which data source to use
DB1_KEYWORDS = [
    "soil",
    "weather",
    "rainfall",
    "temperature",
    "ph",
    "nitrogen",
    "phosphorus",
    "potassium",
]
DB2_KEYWORDS = ["yield", "production", "crop", "area", "hectares", "tonnes"]
LLM_KEYWORDS = [
    "recommend",
    "tips",
    "how to",
    "why",
    "explain",
    "best practices",
    "what is the best",
    "manage",
    "improve",
    "disease",
]

# Known entities the system can recognize
KNOWN_CROPS = ["wheat", "rice", "sugarcane"]
KNOWN_LOCATIONS = [
    "punjab",
    "maharashtra",
    "amritsar",
    "barnala",
    "bathinda",
    "faridkot",
    "fatehgarh sahib",
    "fazilka",
    "ferozepur",
    "gurdaspur",
    "hoshiarpur",
    "jalandhar",
    "kapurthala",
    "ludhiana",
    "mansa",
    "moga",
    "pathankot",
    "patiala",
    "rupnagar",
    "sahibzada ajit singh nagar",
    "sangrur",
    "shahid bhagat singh nagar",
    "sri muktsar sahib",
    "tarn taran",
    "ahmednagar",
    "akola",
    "amravati",
    "aurangabad",
    "beed",
    "bhandara",
    "buldhana",
    "chandrapur",
    "dhule",
    "gadchiroli",
    "gondia",
    "hingoli",
    "jalgaon",
    "jalna",
    "kolhapur",
    "latur",
    "mumbai city",
    "mumbai suburban",
    "nagpur",
    "nanded",
    "nandurbar",
    "nashik",
    "osmanabad",
    "palghar",
    "parbhani",
    "pune",
    "raigad",
    "ratnagiri",
    "sangli",
    "satara",
    "sindhudurg",
    "solapur",
    "thane",
    "wardha",
    "washim",
    "yavatmal",
]

# Simple SQL templates
SQL_TEMPLATES = {
    "avg_yield_by_crop_location_year": "SELECT AVG(hy.yield_ton_per_hectare) FROM historical_yields hy JOIN districts d ON hy.district_id = d.district_id JOIN crops c ON hy.crop_id = c.crop_id WHERE d.district = '<LOCATION>' AND c.crop_name = '<CROP>' AND hy.year = <YEAR>;",
    "avg_ph_by_location": "SELECT AVG(sc.ph_level) FROM soil_conditions sc JOIN districts d ON sc.district_id = d.district_id WHERE d.state = '<LOCATION>';",
    "districts_by_soil_type": "SELECT d.district_id FROM districts d JOIN soil_conditions sc ON d.district_id = sc.district_id WHERE d.state = '<LOCATION>' AND sc.soil_type = '<SOIL_TYPE>';",
    "avg_yield_by_district_list": "SELECT AVG(hy.yield_ton_per_hectare) FROM historical_yields hy JOIN crops c ON hy.crop_id = c.crop_id WHERE c.crop_name = '<CROP>' AND hy.district_id IN <DISTRICT_IDS>;",
}
